export default {
  testEnvironment: 'node',
  transform: {},
  moduleFileExtensions: ['js', 'mjs'],
  testMatch: ['**/tests/**/*.test.js'],
  testPathIgnorePatterns: ['/node_modules/'],
  collectCoverageFrom: [
    'models/**/*.js',
    'routes/**/*.js',
    'utils.js',
    '!**/node_modules/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  verbose: false,
  testTimeout: 30000,
  setupFilesAfterEnv: [],
  moduleNameMapper: {},
  maxWorkers: 1,
  forceExit: true,
  detectOpenHandles: false,
};
